config/routes.rb
Forum::Engine.routes.draw do
  scope '/:locale' do
    resources :articles do
      collection do
        get 'hot'
        get 'latest'
      end
    end

    resources :tags do
      collection do
        get 'hot'
      end
    end

    resources :comments, except: :show do
      collection do
        get 'hot'
        get 'latest'
      end
    end
  end

  root 'articles#latest'
end

app/models/forum/application_record.rb
module Forum
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/forum/article.rb
module Forum
  class Article < ApplicationRecord
    validates :title, :summary, :body, presence: true

    belongs_to :user
    has_many :comments, class_name: 'Forum::Comment', foreign_key: 'forum_article_id'
    has_and_belongs_to_many :tags, class_name: 'Forum::Tag', foreign_key: 'forum_article_id', association_foreign_key: 'forum_tag_id'
  end
end

app/models/forum/comment.rb
module Forum
  class Comment < ApplicationRecord
    validates :forum_article_id, :body, presence: true
    belongs_to :user
    belongs_to :article, class_name: 'Forum::Article', foreign_key: 'forum_article_id'
  end
end

app/models/forum/tag.rb
module Forum
  class Tag < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_and_belongs_to_many :articles, class_name: 'Forum::Article', foreign_key: 'forum_tag_id', association_foreign_key: 'forum_article_id'
  end
end

app/controllers/forum/application_controller.rb
module Forum
  class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception

    before_action :set_locale
    layout 'application'

    def default_url_options
      { locale: I18n.locale }
    end

    protected
    def set_locale
      I18n.locale = params[:locale] || browser.accept_language.first.full
    end
  end
end

app/controllers/forum/articles_controller.rb
require_dependency 'forum/application_controller'

module Forum
  class ArticlesController < ApplicationController
    def hot
      @articles = Article.select(:id, :updated_at, :title, :summary).order(vote: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end

    def latest
      @articles = Article.select(:id, :updated_at, :title, :summary).order(updated_at: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end

    def index
      authorize Article.new
      if current_user.is_admin?
        items = Article.all
      else
        items = Article.where(user_id: current_user.id)
      end
      @articles =  items.select(:id, :title, :updated_at).order(updated_at: :desc).page params[:page]

      render layout: 'dashboard'
    end

    def new
      @article = Article.new
      authorize @article
    end

    def create
      @article = Article.new article_params
      authorize @article

      @article.lang = I18n.locale
      @article.user = current_user
      if @article.save
        redirect_to articles_path
      else
        render 'new'
      end
    end

    def show
      @article = Article.find params[:id]
    end

    def edit
      @article = Article.find params[:id]
      authorize @article
    end

    def update
      @article = Article.find params[:id]
      authorize @article

      if @article.update(article_params)
        redirect_to articles_path
      else
        render 'edit'
      end
    end

    def destroy
      @article = Article.find params[:id]
      authorize @article
      @article.destroy

      redirect_to articles_path
    end

    protected
    def article_params
      params.require(:article).permit(:title, :body, :summary, tag_ids: [])
    end
  end
end

app/controllers/forum/comments_controller.rb
require_dependency 'forum/application_controller'

module Forum
  class CommentsController < ApplicationController
    def hot
      @comments = Comment.order(vote: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end

    def latest
      @comments = Comment.order(updated_at: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end

    def index
      authorize Comment.new
      if current_user.is_admin?
        items = Comment.all
      else
        items = Comment.where(user_id: current_user.id)
      end
      @comments =  items.order(updated_at: :desc).page params[:page]

      render layout: 'dashboard'
    end

    def new
      @comment = Comment.new forum_article_id: params[:article_id]
      authorize @comment
    end

    def create
      @comment = Comment.new params.require(:comment).permit(:forum_article_id, :body)
      authorize @comment

      @comment.user = current_user
      if @comment.save
        redirect_to comments_path
      else
        render 'new'
      end
    end

    def edit
      @comment = Comment.find params[:id]
      authorize @comment
    end

    def update
      @comment = Comment.find params[:id]
      authorize @comment

      if @comment.update(params.require(:comment).permit(:body))
        redirect_to comments_path
      else
        render 'edit'
      end
    end

    def destroy
      @comment = Comment.find params[:id]
      authorize @comment
      @comment.destroy

      redirect_to comments_path
    end

  end
end

app/controllers/forum/home_controller.rb
require_dependency "forum/application_controller"

module Forum
  class HomeController < ApplicationController
    def index
    end

    def dashboard

    end
  end
end

app/controllers/forum/tags_controller.rb
require_dependency 'forum/application_controller'

module Forum
  class TagsController < ApplicationController
    def hot
      @tags = Tag.order(vote: :desc)
    end

    def index
      authorize Tag.new
      @tags = Tag.order(updated_at: :desc)
      render layout: 'dashboard'
    end

    def new
      @tag = Tag.new
      authorize @tag
    end

    def show
      @tag = Tag.find params[:id]
      @articles = @tag.articles.order(vote: :desc).page params[:page]
    end

    def create
      @tag = Tag.new tag_params
      authorize @tag

      @tag.lang = I18n.locale
      if @tag.save
        redirect_to tags_path
      else
        render 'new'
      end
    end

    def edit
      @tag = Tag.find params[:id]
      authorize @tag
    end

    def update
      @tag = Tag.find params[:id]
      authorize @tag

      if @tag.update(tag_params)
        redirect_to tags_path
      else
        render 'edit'
      end
    end

    def destroy
      @tag = Tag.find params[:id]
      authorize @tag
      @tag.destroy

      redirect_to tags_path
    end

    protected
    def tag_params
      params.require(:tag).permit(:name)
    end
  end
end

app/helpers/forum/application_helper.rb
module Forum
  module ApplicationHelper
  end
end

app/views/forum/articles/edit.html.slim
h2
  = @title = t '.title', id: @article.id
hr
= simple_form_for @article do |f|
  = f.input :title
  = f.input :summary, as: :text
  = f.association :tags, as: :check_boxes, include_blank: false
  = f.input :body, as: :text, input_html: {rows: 10}, hint: t('hints.can_markdown')
  = f.button :submit, t('buttons.submit')
  | &nbsp;
  = render 'shared/btn-remove', url:article_path(@article)

app/views/forum/articles/index.html.slim
h2
  = @title = t '.title'
  = link_to t('buttons.new'), new_article_path, class: 'btn btn-link'
hr
= paginate @articles, theme: 'twitter-bootstrap-4'
div class="list-group"
  - @articles.each do |i|
    = link_to i.title, edit_article_path(i), class: 'list-group-item list-group-item-action'

app/views/forum/articles/list.html.slim
h2 #{@title}
hr
= paginate @articles, theme: 'twitter-bootstrap-4'
= render 'forum/shared/articles', items:@articles

app/views/forum/articles/new.html.slim
h2
  = @title = t '.title'
hr
= simple_form_for @article do |f|
  = f.input :title
  = f.input :summary, as: :text
  = f.association :tags, as: :check_boxes, include_blank: false
  = f.input :body, as: :text, input_html: {rows: 10}, hint: t('hints.can_markdown')
  = f.button :submit, t('buttons.submit')

app/views/forum/articles/show.html.slim
h2
  = @title = @article.title
hr
div class="row"
  blockquote class="blockquote"
    p class="mb-0" #{@article.summary}
    footer class="blockquote-footer"
      = time_ago_in_words @article.updated_at
      cite
        - @article.tags.each do |i|
          | &nbsp;
          = link_to i.name, tag_path(i)


div class="row block markdown" #{@article.body}
h3
  = t '.comments'
  - if policy(Forum::Comment.new).update?
    = link_to t('buttons.new'), new_comment_path(article_id:@article.id), class:'btn btn-link', target: :_blank
hr
= render 'forum/shared/comments', items:@article.comments

app/views/forum/comments/edit.html.slim
h2
  = @title = t '.title', id: @comment.id
hr
= simple_form_for @comment do |f|
  = f.input :body, as: :text, input_html: {rows: 10}, hint: t('hints.can_markdown')
  = f.button :submit, t('buttons.submit')
  | &nbsp;
  = render 'shared/btn-remove', url:comment_path(@comment)

app/views/forum/comments/index.html.slim
h2
  = @title = t '.title'
hr
= paginate @comments, theme: 'twitter-bootstrap-4'
div class="list-group"
  - @comments.each do |i|
    = link_to i.body, edit_comment_path(i), class: 'list-group-item list-group-item-action'

app/views/forum/comments/list.html.slim
h2 #{@title}
hr
= paginate @comments, theme: 'twitter-bootstrap-4'

= render 'forum/shared/comments', items:@comments

app/views/forum/comments/new.html.slim
h2
  = @title = t '.title'
hr
= simple_form_for @comment do |f|
  = f.input :forum_article_id, as: :hidden
  = f.input :body, as: :text, input_html: {rows: 10}, hint: t('hints.can_markdown')
  = f.button :submit, t('buttons.submit')

app/views/forum/shared/_articles.html.slim
div class="row"
  -items.each do |i|
    div class="col-md-4"
      div class="card"
        div class="card-block"
          h4 class="card-title"
            = link_to i.title, article_path(i)
          p class="card-text" #{i.summary}
          = link_to t('buttons.view'), article_path(i), class: 'btn btn-secondary', target: :_blank

app/views/forum/shared/_comments.html.slim
-items.each do |i|
  div class="row"
    blockquote class="blockquote"
      p class="mb-0 markdown" #{i.body}
      footer class="blockquote-footer" #{time_ago_in_words i.updated_at}

app/views/forum/tags/edit.html.slim
h2
  = @title = t '.title', id: @tag.id
hr
= simple_form_for @tag do |f|
  = f.input :name
  = f.button :submit, t('buttons.submit')
  | &nbsp;
  = render 'shared/btn-remove', url:tag_path(@tag)

app/views/forum/tags/hot.html.slim
h2
  = @title = t '.title'
hr
div class="row"

app/views/forum/tags/index.html.slim
h2
  = @title = t '.title'
  = link_to t('buttons.new'), new_tag_path, class: 'btn btn-link'
hr
div class="list-group"
  - @tags.each do |i|
    = link_to i.name, edit_tag_path(i), class: 'list-group-item list-group-item-action'

app/views/forum/tags/new.html.slim
h2
  = @title = t '.title'
hr
= simple_form_for @tag do |f|
  = f.input :name
  = f.button :submit, t('buttons.submit')

app/views/forum/tags/show.html.slim
h2
  =@title = t '.title', name:@tag.name
hr
= paginate @articles, theme: 'twitter-bootstrap-4'
= render 'forum/shared/articles', items:@articles

app/views/layouts/forum/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    "forum/application", media: "all" %>
  <%= javascript_include_tag "forum/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>